ZIV_VIAL_CHANCE = 0.18
ZIV_HP_VIAL_CHANCE = 0.6
ZIV_SP_VIAL_CHANCE = 0.4

ZIV_HP_VIAL_HEAL_MIN = 0.1
ZIV_HP_VIAL_HEAL_MAX = 0.15

ZIV_MP_VIAL_MANA_MIN = 0.1
ZIV_MP_VIAL_MANA_MAX = 0.15

ZIV_EP_VIAL_ENERGY_MIN = 0.1
ZIV_EP_VIAL_ENERGY_MAX = 0.15