"CharacterPresets"
{
	"npc_dota_hero_juggernaut"
	{
		"samurai_preset_a"
		{
			"item_bastard_sword" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_ruby_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{

			}
			"item_hunter_gloves"
			{

			}
		}
		"samurai_preset_b"
		{
			"item_bastard_sword" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_topaz_ring" 
			{

			}
			"item_cheap_pants_a"
			{

			}
			"item_snow_boots"
			{

			}
			"item_hunter_gloves"
			{

			}
		}
	}
	"npc_dota_hero_drow_ranger"
	{
		"dark_goddess_preset_a"
		{
			"item_tribe_bow" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_poisonous_quiver"
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
		"dark_goddess_preset_b"
		{
			"item_tribe_bow" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_poisonous_quiver"
			{
				
			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
	}
	"npc_dota_hero_beastmaster"
	{
		"southern_barbarian_preset_a"
		{
			"item_tribe_coat" 
			{

			}
			"item_old_axe" 
			{

			}
			"item_tribe_axe" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
		"southern_barbarian_preset_b"
		{
			"item_tribe_coat" 
			{

			}
			"item_old_axe" 
			{

			}
			"item_tribe_axe" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
	}
	"npc_dota_hero_invoker"
	{
		"elementalist_preset_a"
		{
			"item_tribe_coat" 
			{

			}
			"item_topaz_ring" 
			{

			}
			"item_malachite_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_arcane_gloves"
			{
				
			}
		}
		"elementalist_preset_b"
		{
			"item_tribe_coat" 
			{

			}
			"item_topaz_ring" 
			{

			}
			"item_malachite_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_arcane_gloves"
			{

			}
		}
	}
	"npc_dota_hero_sniper"
	{
		"mercenary_preset_a"
		{
			"item_basic_smg" 
			{

			}
			"item_basic_coat" 
			{

			}
			"item_malachite_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
		"mercenary_preset_b"
		{
			"item_basic_shotgun" 
			{
				
			}
			"item_basic_coat" 
			{

			}
			"item_ruby_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
	}
	"npc_dota_hero_sven"
	{
		"magma_knight_preset_a"
		{
			"item_bastard_sword" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_ruby_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
		"magma_knight_preset_b"
		{
			"item_bastard_sword" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_ruby_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
	}
	"npc_dota_hero_witch_doctor"
	{
		"witch_doctor_preset_a"
		{
			"item_acolyte_staff" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_amethyst_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_wizard_gloves"
			{

			}
		}
		"witch_doctor_preset_b"
		{
			"item_acolyte_staff" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_amethyst_ring" 
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_arcane_gloves"
			{

			}
		}
	}
	"npc_dota_hero_windrunner"
	{
		"huntress_preset_a"
		{
			"item_tribe_bow" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_explosive_quiver"
			{

			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
		"huntress_preset_b"
		{
			"item_tribe_bow" 
			{

			}
			"item_tribe_coat" 
			{

			}
			"item_explosive_quiver"
			{
				
			}
			"item_cheap_pants"
			{
				
			}
			"item_leather_boots"
			{
				
			}
			"item_hunter_gloves"
			{

			}
		}
	}
}