"CharacterPresets"
{
	"npc_dota_hero_sniper"
	{
		"mercenary_preset_a"
		{
			"item_basic_smg" 
			{

			}
			"item_basic_coat" 
			{
				"10" "item_gem_malachite"
				"50" "item_gem_malachite"
			}
		}
		"mercenary_preset_b"
		{
			"item_basic_shotgun" 
			{
				
			}
		}
	}
	"npc_dota_hero_sven"
	{
		"magma_knight_preset_a"
		{
			"item_bastard_sword" 
			{

			}
			"item_tribe_coat" 
			{

			}
		}
	}
}