"Recipes"
{
	"random_iron_axe_2" 
	{
		"Parts" 
		{
			"item_craft_iron"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_old_axe"  "1"
			"item_tribe_axe"  "1"
			"item_wood_axe"  "1"
		}
	}
	"random_iron_axe_3" 
	{
		"Parts" 
		{
			"item_craft_gold"  "1"
			"item_craft_iron"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_old_axe"  "1"
			"item_tribe_axe"  "1"
			"item_wood_axe"  "1"
		}
	}
	"random_iron_axe_4" 
	{
		"Parts" 
		{
			"item_craft_gold"  "2"
			"item_craft_iron"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_old_axe"  "1"
			"item_tribe_axe"  "1"
			"item_wood_axe"  "1"
		}
	}
	"random_iron_gun_2" 
	{
		"Parts" 
		{
			"item_craft_iron"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_basic_shotgun"  "1"
			"item_basic_smg"  "1"
			"item_craft_shotgun"  "1"
			"item_enhanced_shotgun"  "1"
		}
	}
	"random_iron_gun_3" 
	{
		"Parts" 
		{
			"item_craft_gold"  "1"
			"item_craft_iron"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_basic_shotgun"  "1"
			"item_basic_smg"  "1"
			"item_craft_shotgun"  "1"
			"item_enhanced_shotgun"  "1"
		}
	}
	"random_iron_gun_4" 
	{
		"Parts" 
		{
			"item_craft_gold"  "2"
			"item_craft_iron"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_basic_shotgun"  "1"
			"item_basic_smg"  "1"
			"item_craft_shotgun"  "1"
			"item_enhanced_shotgun"  "1"
		}
	}
	"random_iron_sword_2" 
	{
		"Parts" 
		{
			"item_craft_iron"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_basic_sword"  "1"
			"item_bastard_sword"  "1"
			"item_scarred_sword"  "1"
		}
	}
	"random_iron_sword_3" 
	{
		"Parts" 
		{
			"item_craft_gold"  "1"
			"item_craft_iron"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_basic_sword"  "1"
			"item_bastard_sword"  "1"
			"item_scarred_sword"  "1"
		}
	}
	"random_iron_sword_4" 
	{
		"Parts" 
		{
			"item_craft_gold"  "2"
			"item_craft_iron"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_basic_sword"  "1"
			"item_bastard_sword"  "1"
			"item_scarred_sword"  "1"
		}
	}
	"random_leather_boots_2" 
	{
		"Parts" 
		{
			"item_craft_leather"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_leather_boots"  "1"
			"item_ornate_boots"  "1"
			"item_snow_boots"  "1"
		}
	}
	"random_leather_boots_3" 
	{
		"Parts" 
		{
			"item_craft_leather"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_leather_boots"  "1"
			"item_ornate_boots"  "1"
			"item_snow_boots"  "1"
		}
	}
	"random_leather_boots_4" 
	{
		"Parts" 
		{
			"item_craft_leather"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_leather_boots"  "1"
			"item_ornate_boots"  "1"
			"item_snow_boots"  "1"
		}
	}
	"random_leather_pants_2" 
	{
		"Parts" 
		{
			"item_craft_leather"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_cheap_pants"  "1"
			"item_cheap_pants_a"  "1"
			"item_cheap_pants_b"  "1"
		}
	}
	"random_leather_pants_3" 
	{
		"Parts" 
		{
			"item_craft_leather"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_cheap_pants"  "1"
			"item_cheap_pants_a"  "1"
			"item_cheap_pants_b"  "1"
		}
	}
	"random_leather_pants_4" 
	{
		"Parts" 
		{
			"item_craft_leather"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_cheap_pants"  "1"
			"item_cheap_pants_a"  "1"
			"item_cheap_pants_b"  "1"
		}
	}
	"random_leather_torso_2" 
	{
		"Parts" 
		{
			"item_craft_leather"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_arrow_proof_coat"  "1"
			"item_basic_coat"  "1"
			"item_tribe_coat"  "1"
		}
	}
	"random_leather_torso_3" 
	{
		"Parts" 
		{
			"item_craft_leather"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_arrow_proof_coat"  "1"
			"item_basic_coat"  "1"
			"item_tribe_coat"  "1"
		}
	}
	"random_leather_torso_4" 
	{
		"Parts" 
		{
			"item_craft_leather"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_arrow_proof_coat"  "1"
			"item_basic_coat"  "1"
			"item_tribe_coat"  "1"
		}
	}
	"random_ore_ring_2" 
	{
		"Parts" 
		{
			"item_craft_ore"  "4"
			"item_craft_parts"  "2"
		}
		"PossibleResults" 
		{
			"item_amethyst_ring"  "1"
			"item_malachite_ring"  "1"
			"item_ruby_ring"  "1"
			"item_topaz_ring"  "1"
		}
	}
	"random_ore_ring_3" 
	{
		"Parts" 
		{
			"item_craft_ore"  "6"
			"item_craft_parts"  "3"
		}
		"PossibleResults" 
		{
			"item_amethyst_ring"  "1"
			"item_malachite_ring"  "1"
			"item_ruby_ring"  "1"
			"item_topaz_ring"  "1"
		}
	}
	"random_ore_ring_4" 
	{
		"Parts" 
		{
			"item_craft_ore"  "8"
			"item_craft_parts"  "4"
		}
		"PossibleResults" 
		{
			"item_amethyst_ring"  "1"
			"item_malachite_ring"  "1"
			"item_ruby_ring"  "1"
			"item_topaz_ring"  "1"
		}
	}
	"random_wood_bow_2" 
	{
		"Parts" 
		{
			"item_craft_parts"  "2"
			"item_craft_wood"  "4"
		}
		"PossibleResults" 
		{
			"item_basic_bow"  "1"
			"item_craft_bow"  "1"
			"item_tribe_bow"  "1"
		}
	}
	"random_wood_bow_3" 
	{
		"Parts" 
		{
			"item_craft_parts"  "3"
			"item_craft_wood"  "6"
		}
		"PossibleResults" 
		{
			"item_basic_bow"  "1"
			"item_craft_bow"  "1"
			"item_tribe_bow"  "1"
		}
	}
	"random_wood_bow_4" 
	{
		"Parts" 
		{
			"item_craft_parts"  "4"
			"item_craft_wood"  "8"
		}
		"PossibleResults" 
		{
			"item_basic_bow"  "1"
			"item_craft_bow"  "1"
			"item_tribe_bow"  "1"
		}
	}
	"random_wood_quiver_2" 
	{
		"Parts" 
		{
			"item_craft_parts"  "2"
			"item_craft_wood"  "4"
		}
		"PossibleResults" 
		{
			"item_explosive_quiver"  "1"
			"item_frost_quiver"  "1"
			"item_poisonous_quiver"  "1"
		}
	}
	"random_wood_quiver_3" 
	{
		"Parts" 
		{
			"item_craft_parts"  "3"
			"item_craft_wood"  "6"
		}
		"PossibleResults" 
		{
			"item_explosive_quiver"  "1"
			"item_frost_quiver"  "1"
			"item_poisonous_quiver"  "1"
		}
	}
	"random_wood_quiver_4" 
	{
		"Parts" 
		{
			"item_craft_parts"  "4"
			"item_craft_wood"  "8"
		}
		"PossibleResults" 
		{
			"item_explosive_quiver"  "1"
			"item_frost_quiver"  "1"
			"item_poisonous_quiver"  "1"
		}
	}
	"random_wood_staff_2" 
	{
		"Parts" 
		{
			"item_craft_parts"  "2"
			"item_craft_wood"  "4"
		}
		"PossibleResults" 
		{
			"item_acolyte_staff"  "1"
			"item_druid_staff"  "1"
			"item_elven_staff"  "1"
		}
	}
	"random_wood_staff_3" 
	{
		"Parts" 
		{
			"item_craft_parts"  "3"
			"item_craft_wood"  "6"
		}
		"PossibleResults" 
		{
			"item_acolyte_staff"  "1"
			"item_druid_staff"  "1"
			"item_elven_staff"  "1"
		}
	}
	"random_wood_staff_4" 
	{
		"Parts" 
		{
			"item_craft_parts"  "4"
			"item_craft_wood"  "8"
		}
		"PossibleResults" 
		{
			"item_acolyte_staff"  "1"
			"item_druid_staff"  "1"
			"item_elven_staff"  "1"
		}
	}
}